Image:
  extensions:
    - 'ImageExtension'
SiteConfig:
  extensions:
    - 'SiteConfigExtension'
ProjectPage:
  extensions:
    - 'FigureExtension'
BlogPost:
  extensions:
    - 'FigureExtension'
#    - CommentsExtension